### ISSUE TITLE
Pretrained embeddings vocab size mismatch

### ISSUE THREAD

**Issue by danlou** [nguyenkh/HyperVec#1]
Hi Kim,

I've downloaded the pretrained embeddings using the .sh you provide and found that the doc resulting from the concatenation only has 1.8M lines, significantly fewer than the 2.7M indicated in the README.

Can you let us know if the embeddings available for download actually reflect the training configuration specified in the README, and if these embeddings give the same score on Hyperlex as described in the paper?

Thanks!

**Comment by nguyenkh** [comment]
Hi danlou,

Sorry for the late reply. The part_0 was missing, so I have fixed it.

Yes, we used this embeddings for our experiments in the paper.

**Comment by ZacharyChenpk** [comment]
> Hi danlou,
> 
> Sorry for the late reply. The part_0 was missing, so I have fixed it.
> 
> Yes, we used this embeddings for our experiments in the paper.

Hi, I have recently downloaded the pretrained embeddings, and found that there are only 2M lines in hypervec.txt.gz, mismatching the 2.7M indicated in the first line. Maybe the embedding files are still uncomplete?
